<?php
if(!isset($_SESSION)){session_start();}

require $_SERVER['DOCUMENT_ROOT']."/components/inputs/pieces/selects/pieces/open_select_and_include_functions.php";

produce_option("Accountant",						$selected);
produce_option("Accountant – Virtual CFO",				$selected);
produce_option("Acupuncture",						$selected);
produce_option("Ad Agency",						$selected);
produce_option("Administration Support",				$selected);
produce_option("Advertising - Internet",				$selected);
produce_option("Advertising - N'paper - Magazines - Publications",	$selected);
produce_option("Advertising - Radio",					$selected);
produce_option("Advertising - TV",					$selected);
produce_option("Advertising & Design",					$selected);
produce_option("Aged Care Provider",					$selected);
produce_option("Air Conditioning",					$selected);
produce_option("Air Conditioning - Commercial",				$selected);
produce_option("Air Conditioning - Refrigeration",			$selected);
produce_option("Air Conditioning - Residential",			$selected);
produce_option("Alarm Systems Sales and Installation",			$selected);
produce_option("Anti Ageing",						$selected);
produce_option("Anti-Ageing Technology Products",			$selected);
produce_option("Apartments/Accommodation",				$selected);
produce_option("App Development",					$selected);
produce_option("Appliance Sales",					$selected);
produce_option("Apprenticeship Consultant",				$selected);
produce_option("Arborist",						$selected);
produce_option("Architect",						$selected);
produce_option("Asbestos Removal",					$selected);
produce_option("Asset Finance",						$selected);
produce_option("Asset Finance - Commercial",				$selected);
produce_option("Audio Visual Branding",					$selected);
produce_option("Audio Visual Solutions",				$selected);
produce_option("Auto Electician",					$selected);
produce_option("Automotive Service & Repairs",				$selected);
produce_option("Bar",							$selected);
produce_option("Bathroom Renovations",					$selected);
produce_option("Beauty Products",					$selected);
produce_option("Beauty Salon",						$selected);
produce_option("Beauty Therapy",					$selected);
produce_option("Bed and Breakfast",					$selected);
produce_option("Beverage Supplier",					$selected);
produce_option("Blade Sharpening & Sales",				$selected);
produce_option("Body Corporate Management",				$selected);
produce_option("Bookkeeper",						$selected);
produce_option("Bowen Therapist",					$selected);
produce_option("Brand Management",					$selected);
produce_option("Brand Strategy",					$selected);
produce_option("Budget Coach",						$selected);
produce_option("Builder - Commercial",					$selected);
produce_option("Builder - Domestic",					$selected);
produce_option("Builder - General Contractor",				$selected);
produce_option("Builder - Minor Works",					$selected);
produce_option("Builder - New Homes",					$selected);
produce_option("Builder - Renovations",					$selected);
produce_option("Builders and Office Cleaning",				$selected);
produce_option("Building Consultant",					$selected);
produce_option("Building Designer",					$selected);
produce_option("Building Development",					$selected);
produce_option("Building Inspection - Certification",			$selected);
produce_option("Building Inspection - Pre Purchase Reports",		$selected);
produce_option("Building Maintenance Project Management",		$selected);
produce_option("Building Repairs & Maintenance",			$selected);
produce_option("Building-Trades",					$selected);
produce_option("Business Advisory Consultant",				$selected);
produce_option("Business Analyst",					$selected);
produce_option("Business Broker",					$selected);
produce_option("Business Coach",					$selected);
produce_option("Business Consultant",					$selected);
produce_option("Business Development",					$selected);
produce_option("Business Finance",					$selected);
produce_option("Business Insurance",					$selected);
produce_option("Business Law",						$selected);
produce_option("Business Machines",					$selected);
produce_option("Business Marketing Systems",				$selected);
produce_option("Business Process Improvement",				$selected);
produce_option("Business Risk Insurance",				$selected);
produce_option("Business Service Centre",				$selected);
produce_option("Business Services Advisor",				$selected);
produce_option("Business Services Large Clients",			$selected);
produce_option("Business Services Small Clients",			$selected);
produce_option("Business Software Solutions Provider",			$selected);
produce_option("Business System Consultant",				$selected);
produce_option("Business Technology Services - Over 10 Employees",	$selected);
produce_option("Business Technology Services - Under 10 Employees",	$selected);
produce_option("Business Training",					$selected);
produce_option("Buyers Agent",						$selected);
produce_option("Cabinet Maker",						$selected);
produce_option("Cafe",							$selected);
produce_option("Capacity Building Consultant",				$selected);
produce_option("Car Maintenance",					$selected);
produce_option("Car Sales",						$selected);
produce_option("Car Sharing",						$selected);
produce_option("Carpenter",						$selected);
produce_option("Carpet Cleaner",					$selected);
produce_option("Caterer",						$selected);
produce_option("CCTV Sales & Installation",				$selected);
produce_option("Ceiling & Wall Repairs",				$selected);
produce_option("Celebrant",						$selected);
produce_option("CFO/CEO Services",					$selected);
produce_option("Chartered Accountant",					$selected);
produce_option("Chauffeur Services",					$selected);
produce_option("Chiropractor",						$selected);
produce_option("Civil Engineering",					$selected);
produce_option("Civil Marriage Celebrant",				$selected);
produce_option("Cleaning / Contractor",					$selected);
produce_option("Cleaning Products",					$selected);
produce_option("Cloud Software Integration",				$selected);
produce_option("Coach - Business Growth Expert",			$selected);
produce_option("Coaching - Human Resources Consultant",			$selected);
produce_option("Coffee Supply & Service",				$selected);
produce_option("Commercial Banking",					$selected);
produce_option("Commercial Business Finance",				$selected);
produce_option("Commercial Cleaning Services",				$selected);
produce_option("Commercial electrician, data & fibre cabling",		$selected);
produce_option("Commercial Facilities Management",			$selected);
produce_option("Commercial Finance",					$selected);
produce_option("Commercial Fitouts",					$selected);
produce_option("Commercial Insurance",					$selected);
produce_option("Commercial IT",						$selected);
produce_option("Commercial Law",					$selected);
produce_option("Commercial Office Cleaning",				$selected);
produce_option("Commercial Office Furniture",				$selected);
produce_option("Commercial Photography",				$selected);
produce_option("Commercial Property Advisory and Support",		$selected);
produce_option("Commercial Property Management",			$selected);
produce_option("Commercial Real Estate – Sales",			$selected);
produce_option("Commercial Videography",				$selected);
produce_option("Communication Systems",					$selected);
produce_option("Communications Consultant",				$selected);
produce_option("Community Care & Support Services",			$selected);
produce_option("Community Marketing",					$selected);
produce_option("Community Services/ Charity",				$selected);
produce_option("Computer Consultant",					$selected);
produce_option("Computer Hardware",					$selected);
produce_option("Computer Repairs",					$selected);
produce_option("Concierge and Errand Services",				$selected);
produce_option("Concrete Work Incl Floors",				$selected);
produce_option("Construction Law",					$selected);
produce_option("Construction Management",				$selected);
produce_option("Content Creation",					$selected);
produce_option("Conveyancing",						$selected);
produce_option("Copiers & Printers",					$selected);
produce_option("Copy Shop",						$selected);
produce_option("Copywriting",						$selected);
produce_option("Corporate Gifts",					$selected);
produce_option("Corporate Health Programmes",				$selected);
produce_option("Corporate Law",						$selected);
produce_option("Cosmetic Surgeon",					$selected);
produce_option("Counselling",						$selected);
produce_option("Counselor Psychotherapist",				$selected);
produce_option("Coworking Office Space",				$selected);
produce_option("Criminal Law",						$selected);
produce_option("Curtains and Blinds",					$selected);
produce_option("Custom Software Development",				$selected);
produce_option("Customer Journey Mapping",				$selected);
produce_option("Dance Instruction",					$selected);
produce_option("Debt Recovery",						$selected);
produce_option("Decking & Pergolas",					$selected);
produce_option("Dentist",						$selected);
produce_option("Dietician",						$selected);
produce_option("Digital Advertising",					$selected);
produce_option("Digital Communications -- Business Apps",		$selected);
produce_option("Digital Marketing Consultant",				$selected);
produce_option("Digital Photography",					$selected);
produce_option("Digital Printing",					$selected);
produce_option("Disability Employment",					$selected);
produce_option("Disability Support Services",				$selected);
produce_option("Display Systems",					$selected);
produce_option("Dispute Resolution/Mediation",				$selected);
produce_option("Dog Trainer",						$selected);
produce_option("Domestic Cleaning Services",				$selected);
produce_option("Drone Services",					$selected);
produce_option("Earthworks",						$selected);
produce_option("Editing",						$selected);
produce_option("Electrical Contractor",					$selected);
produce_option("Electrical Contractor – Commercial",			$selected);
produce_option("Electrical Contractor – Residential",			$selected);
produce_option("Electrician",						$selected);
produce_option("Electrician - Solar Power",				$selected);
produce_option("Electronic Services - Audio and Video",			$selected);
produce_option("Electronics Repairs",					$selected);
produce_option("Embroidery",						$selected);
produce_option("Employment Consultant",					$selected);
produce_option("Energy Coach",						$selected);
produce_option("Engineer/Consultant (including Structural)",		$selected);
produce_option("Entertainer",						$selected);
produce_option("Entertainment",						$selected);
produce_option("Environmental Science",					$selected);
produce_option("Environmental/Energy Consultants",			$selected);
produce_option("Equipment Finance",					$selected);
produce_option("Equipment Testing",					$selected);
produce_option("Essential Oils",					$selected);
produce_option("Essential Services",					$selected);
produce_option("Estate Law",						$selected);
produce_option("Event – Venues",					$selected);
produce_option("Event Management",					$selected);
produce_option("Events Management",					$selected);
produce_option("Events Marketing",					$selected);
produce_option("Executive Coaching",					$selected);
produce_option("Executive Recruitment",					$selected);
produce_option("Exercise Physiology",					$selected);
produce_option("Family Law",						$selected);
produce_option("Fence Contractor",					$selected);
produce_option("Feng Shui Consultant",					$selected);
produce_option("Feng Shui Practitioner",				$selected);
produce_option("Film and Video Producer",				$selected);
produce_option("Finance - Motor Vehicle & Marine",			$selected);
produce_option("Finance Broker",					$selected);
produce_option("Finance Broker - Business",				$selected);
produce_option("Finance Broker - Commercial",				$selected);
produce_option("Financial Advisor",					$selected);
produce_option("Financial Advisor - Risk",				$selected);
produce_option("Financial Advisor – Wealth and Super",			$selected);
produce_option("Financial Ancillary",					$selected);
produce_option("Financial Consultant",					$selected);
produce_option("Financial Education and Coaching", 			$selected);
produce_option("Financial Planner", 					$selected);
produce_option("Financial Planner - Personal Risk", 			$selected);
produce_option("Financial Planner - Wealth and Superannuation", 	$selected);
produce_option("Financial Planner - Wealth creation", 			$selected);
produce_option("Fire Protection & Equipment", 				$selected);
produce_option("First Aid Supplies", 					$selected);
produce_option("Fitness Centre", 					$selected);
produce_option("Floor & Tile Cleaning", 				$selected);
produce_option("Floor Coverings", 					$selected);
produce_option("Floor Heating", 					$selected);
produce_option("Floor Restoration", 					$selected);
produce_option("Flooring", 						$selected);
produce_option("Flooring Installation - Commercial", 			$selected);
produce_option("Florist", 						$selected);
produce_option("Food Safety Technology", 				$selected);
produce_option("Footwear", 						$selected);
produce_option("Freight Management/Transport", 				$selected);
produce_option("Fundraising", 						$selected);
produce_option("Funeral Director", 					$selected);
produce_option("Furniture Dealer", 					$selected);
produce_option("Furniture Repair", 					$selected);
produce_option("Garage Door Repairs", 					$selected);
produce_option("Gardening", 						$selected);
produce_option("Genealogy Specialist", 					$selected);
produce_option("General Insurance", 					$selected);
produce_option("General Insurance Broker", 				$selected);
produce_option("General Maintenance", 					$selected);
produce_option("Geotechnical Engineer", 				$selected);
produce_option("Gift Baskets", 						$selected);
produce_option("Gift Services", 					$selected);
produce_option("Gifts", 						$selected);
produce_option("Giftware", 						$selected);
produce_option("Glazier", 						$selected);
produce_option("Google Adwords", 					$selected);
produce_option("Government Grants", 					$selected);
produce_option("Graphic Design", 					$selected);
produce_option("Graphic Design and Communication", 			$selected);
produce_option("Graphic Design and Illustration", 			$selected);
produce_option("Grounds Maintenance", 					$selected);
produce_option("Guided Tours", 						$selected);
produce_option("Gutter & Roof Cleaning – Domestic & Commercial", 	$selected);
produce_option("Gutter Protection", 					$selected);
produce_option("Hair & Makeup Artist", 					$selected);
produce_option("Hairdresser", 						$selected);
produce_option("Handyman", 						$selected);
produce_option("Health & Wellbeing Coaching", 				$selected);
produce_option("Health & Wellness Services", 				$selected);
produce_option("Health and Fitness Coach", 				$selected);
produce_option("Health and Wellness - Products", 			$selected);
produce_option("Health Coach", 						$selected);
produce_option("Health Products", 					$selected);
produce_option("Heating", 						$selected);
produce_option("High Performance Coach", 				$selected);
produce_option("Home Automation & Control Systems", 			$selected);
produce_option("Home Lending", 						$selected);
produce_option("Home Organiser", 					$selected);
produce_option("Home Staging", 						$selected);
produce_option("Homeopath", 						$selected);
produce_option("Horticulturist", 					$selected);
produce_option("Hospitality Consultancy", 				$selected);
produce_option("Hospitality Technology", 				$selected);
produce_option("Human Capital", 					$selected);
produce_option("Human Resource Consultant", 				$selected);
produce_option("Hypnotherapy", 						$selected);
produce_option("Image Consultant", 					$selected);
produce_option("Immigration Services", 					$selected);
produce_option("Import/Export", 					$selected);
produce_option("Inbound & Content Marketing", 				$selected);
produce_option("Indoor Cleaning", 					$selected);
produce_option("Industrial Relations", 					$selected);
produce_option("Industrial Supplies", 					$selected);
produce_option("Insolvency & Recovery Services", 			$selected);
produce_option("Insurance Broker", 					$selected);
produce_option("Insurance Law", 					$selected);
produce_option("Intellectual Property & Trademark Lawyer", 		$selected);
produce_option("Interior Design", 					$selected);
produce_option("International Freight Forwarding", 			$selected);
produce_option("Internet Marketing", 					$selected);
produce_option("Investment", 						$selected);
produce_option("Investment Capital", 					$selected);
produce_option("Investment Property", 					$selected);
produce_option("Investment Property – Commercial", 			$selected);
produce_option("Invoice Finance", 					$selected);
produce_option("IT Consulting", 					$selected);
produce_option("IT Security", 						$selected);
produce_option("IT Services", 						$selected);
produce_option("IT Support", 						$selected);
produce_option("Jewellery Design and Manufacture", 			$selected);
produce_option("Kinesiology", 						$selected);
produce_option("Kitchen Installations", 				$selected);
produce_option("Kitchens", 						$selected);
produce_option("Landlord and Tenant Services", 				$selected);
produce_option("Landscape Design & Construction", 			$selected);
produce_option("Landscaper", 						$selected);
produce_option("Law - Commercial Litigation", 				$selected);
produce_option("Lawn Mowing", 						$selected);
produce_option("Lawyer", 						$selected);
produce_option("Lawyer - Commercial", 					$selected);
produce_option("Lawyer - Taxation Law", 				$selected);
produce_option("Lead Generation", 					$selected);
produce_option("Leadership Coach", 					$selected);
produce_option("Leather Repair, Care and Restoration", 			$selected);
produce_option("Legal - Estate and Succession Planning",		$selected);
produce_option("Legal Services", 					$selected);
produce_option("Licensed Land Surveyor", 				$selected);
produce_option("Life Coach", 						$selected);
produce_option("Life Insurance", 					$selected);
produce_option("Litigation Law", 					$selected);
produce_option("Locksmith", 						$selected);
produce_option("Luxury Home Design & Development", 			$selected);
produce_option("Maintenance & Support", 				$selected);
produce_option("Managed IT Service", 					$selected);
produce_option("Management Accounting Specialist", 			$selected);
produce_option("Management Consultant", 				$selected);
produce_option("Marketing Consultant", 					$selected);
produce_option("Marketing Consultant - Branding & Identity", 		$selected);
produce_option("Marketing Management", 					$selected);
produce_option("Marketing Plans", 					$selected);
produce_option("Marketing Strategy", 					$selected);
produce_option("Martial Arts", 						$selected);
produce_option("Massage Therapist", 					$selected);
produce_option("Mechanical Workshop", 					$selected);
produce_option("Media Sales", 						$selected);
produce_option("Merchant Banker", 					$selected);
produce_option("Migration Agent", 					$selected);
produce_option("Migration Lawyer", 					$selected);
produce_option("Mind Coach", 						$selected);
produce_option("Mindset Coach", 					$selected);
produce_option("Mobile Knife Sharpener", 				$selected);
produce_option("Mobile Mechanic", 					$selected);
produce_option("Mobile Phones", 					$selected);
produce_option("Mobile Travel Agent", 					$selected);
produce_option("Mortgage Broker - Residential", 			$selected);
produce_option("Mortgage Broker – Commercial", 				$selected);
produce_option("Mortgage Investment", 					$selected);
produce_option("Motor Mechanic", 					$selected);
produce_option("Motor Vehicle Finance", 				$selected);
produce_option("Music Tuition", 					$selected);
produce_option("Myotherapy", 						$selected);
produce_option("Natural Health Marketing", 				$selected);
produce_option("Natural Therapies", 					$selected);
produce_option("Naturopath", 						$selected);
produce_option("New & Used Vehicle sales", 				$selected);
produce_option("Non For Profit", 					$selected);
produce_option("Nonfiction Author Coach", 				$selected);
produce_option("Nutrition", 						$selected);
produce_option("Nutritional Cleansing System", 				$selected);
produce_option("Nutritional Products", 					$selected);
produce_option("Occupational Therapist", 				$selected);
produce_option("Office and Hospitality Fitout", 			$selected);
produce_option("Office Equipment", 					$selected);
produce_option("Office Furniture", 					$selected);
produce_option("Office Machines", 					$selected);
produce_option("Office Supplies", 					$selected);
produce_option("Online Marketing - AdWords", 				$selected);
produce_option("Online Marketing - Video Production", 			$selected);
produce_option("Online Marketing - Web Design & Development", 		$selected);
produce_option("Online Marketing and Branding", 			$selected);
produce_option("Optical", 						$selected);
produce_option("Osteopath", 						$selected);
produce_option("Outdoor Living Areas", 					$selected);
produce_option("Outdoor Renovation", 					$selected);
produce_option("Pain Management Devices", 				$selected);
produce_option("Paint Sales", 						$selected);
produce_option("Painter", 						$selected);
produce_option("Painter- Residential", 					$selected);
produce_option("Painting and Decorating", 				$selected);
produce_option("Patent and/or Trade Mark and/or Design Attorney", 	$selected);
produce_option("Peak Performance Strategist", 				$selected);
produce_option("Personal Budgeting", 					$selected);
produce_option("Personal Coach", 					$selected);
produce_option("Personal Development", 					$selected);
produce_option("Personal Fitness Trainer", 				$selected);
produce_option("Personal Injury Lawyer", 				$selected);
produce_option("Personal Insurance Broker", 				$selected);
produce_option("Personal Risk Insurance", 				$selected);
produce_option("Pest Control", 						$selected);
produce_option("Pest Control Maintenance", 				$selected);
produce_option("Pet Care", 						$selected);
produce_option("Photocopier Service", 					$selected);
produce_option("Photographer", 						$selected);
produce_option("Physiotherapist", 					$selected);
produce_option("Pilates", 						$selected);
produce_option("Plasterer", 						$selected);
produce_option("Plumber", 						$selected);
produce_option("Plumber Gas Fitter", 					$selected);
produce_option("Plumber Residential", 					$selected);
produce_option("Plumbing & Gas", 					$selected);
produce_option("Podiatrist", 						$selected);
produce_option("Pool Main/Service", 					$selected);
produce_option("Pools/Installation", 					$selected);
produce_option("Portrait Photography", 					$selected);
produce_option("Print Broker", 						$selected);
produce_option("Print Management", 					$selected);
produce_option("Print Solutions", 					$selected);
produce_option("Printer", 						$selected);
produce_option("Private Taxi", 						$selected);
produce_option("Professional Organiser", 				$selected);
produce_option("Professional Speaker", 					$selected);
produce_option("Professional Training & Coaching", 			$selected);
produce_option("Project Manager - Commercial", 				$selected);
produce_option("Project Manager - Residential", 			$selected);
produce_option("Promotional Products", 					$selected);
produce_option("Property & Conveyancing", 				$selected);
produce_option("Property Advocate", 					$selected);
produce_option("Property Consultant", 					$selected);
produce_option("Property Developer", 					$selected);
produce_option("Property Inspections", 					$selected);
produce_option("Property Investment Advisor", 				$selected);
produce_option("Property Law", 						$selected);
produce_option("Property Maintenance", 					$selected);
produce_option("Property Management", 					$selected);
produce_option("Property Management - Residential", 			$selected);
produce_option("Property Management – Renters Agent", 			$selected);
produce_option("Property Mentor", 					$selected);
produce_option("Property Stylist", 					$selected);
produce_option("Property Subdivision", 					$selected);
produce_option("Property Valuations and Advisory", 			$selected);
produce_option("Protective Coatings", 					$selected);
produce_option("Providore", 						$selected);
produce_option("Psychologist", 						$selected);
produce_option("Psychotherapist", 					$selected);
produce_option("Public Relations", 					$selected);
produce_option("Public Speaker", 					$selected);
produce_option("Publisher - Book and Other", 				$selected);
produce_option("Quality Management Consultant", 			$selected);
produce_option("Quantity Surveyor", 					$selected);
produce_option("Real Estate - Commercial", 				$selected);
produce_option("Real Estate - Home Presentation Services", 		$selected);
produce_option("Real Estate - Project Marketing & Sales", 		$selected);
produce_option("Real Estate Agent - Residential", 			$selected);
produce_option("Real Estate Buyers Agent", 				$selected);
produce_option("Real Estate Consultant & Training", 			$selected);
produce_option("Real Estate Tax Depreciation", 				$selected);
produce_option("Recruitment Consultant", 				$selected);
produce_option("Registered Training Organisation", 			$selected);
produce_option("Reiki Practitioner", 					$selected);
produce_option("Relationship Marketing", 				$selected);
produce_option("Relocations", 						$selected);
produce_option("Remedial Massage Therapist", 				$selected);
produce_option("Removalist", 						$selected);
produce_option("Renewable Energy", 					$selected);
produce_option("Renovations & Maintenance", 				$selected);
produce_option("Reputation Marketing", 					$selected);
produce_option("Residential Cleaning Services", 			$selected);
produce_option("Residential Real Estate - Sales", 			$selected);
produce_option("Residential Real Estate – Sales", 			$selected);
produce_option("Restaurant / Cafe / Food Outlet", 			$selected);
produce_option("Roof Plumber", 						$selected);
produce_option("Roofing and Roof Restoration", 				$selected);
produce_option("Rubbish Removal", 					$selected);
produce_option("Safety and Workplace Relations", 			$selected);
produce_option("Sales and Marketing Strategy", 				$selected);
produce_option("Sales Coaching", 					$selected);
produce_option("Sales Management Consultant", 				$selected);
produce_option("Sales Presentation Skills", 				$selected);
produce_option("Sales Training", 					$selected);
produce_option("Scaffolding", 						$selected);
produce_option("Screens & Blinds", 					$selected);
produce_option("Search Engine Marketing", 				$selected);
produce_option("Search Engine Optimisation", 				$selected);
produce_option("Security Doors Windows Screens", 			$selected);
produce_option("Security Monitoring", 					$selected);
produce_option("Security Services", 					$selected);
produce_option("Security Systems", 					$selected);
produce_option("Send out Cards", 					$selected);
produce_option("Settlement Agent", 					$selected);
produce_option("Shopfitter", 						$selected);
produce_option("Sign Maker", 						$selected);
produce_option("Signage", 						$selected);
produce_option("Signwriter", 						$selected);
produce_option("Skincare", 						$selected);
produce_option("Skip Bin Hire", 					$selected);
produce_option("Smash Repairs", 					$selected);
produce_option("Smoke Alarm Testing", 					$selected);
produce_option("SMSF Advisor", 						$selected);
produce_option("Social Media Management", 				$selected);
produce_option("Social Media Marketing", 				$selected);
produce_option("Social Media Strategist", 				$selected);
produce_option("Software – Business Information Systems", 		$selected);
produce_option("Software Application & Game Development", 		$selected);
produce_option("Solar Energy", 						$selected);
produce_option("Solar PV & Energy Efficiency", 				$selected);
produce_option("Solicitor", 						$selected);
produce_option("Spa Therapist", 					$selected);
produce_option("Spas/Installation", 					$selected);
produce_option("Speaker Coach", 					$selected);
produce_option("Speciality Gifts", 					$selected);
produce_option("Specialty Printer", 					$selected);
produce_option("Staff Management Solutions", 				$selected);
produce_option("Staff Outsourcing Services", 				$selected);
produce_option("Stainless Steel Fabrication", 				$selected);
produce_option("Stationery Supplies", 					$selected);
produce_option("Stockbroker", 						$selected);
produce_option("Stonemason", 						$selected);
produce_option("Storage", 						$selected);
produce_option("Strata Management", 					$selected);
produce_option("Strategic Advisor", 					$selected);
produce_option("Success Strategist", 					$selected);
produce_option("Sunglasses", 						$selected);
produce_option("Tailor", 						$selected);
produce_option("Tax Accountant", 					$selected);
produce_option("Tax Consulting", 					$selected);
produce_option("Taxation", 						$selected);
produce_option("Telecommunications", 					$selected);
produce_option("Telephone Message Service", 				$selected);
produce_option("Telephone Systems", 					$selected);
produce_option("Tennis Coach", 						$selected);
produce_option("Testing & Tagging", 					$selected);
produce_option("Tile & Grout Restoration", 				$selected);
produce_option("Tile Retailer", 					$selected);
produce_option("Tiler", 						$selected);
produce_option("Toners & Cartridges", 					$selected);
produce_option("Tour Operator and Tours", 				$selected);
produce_option("Town Planner", 						$selected);
produce_option("Town Planning & Certification", 			$selected);
produce_option("Trademark Specialist / Consultant", 			$selected);
produce_option("Training & Development", 				$selected);
produce_option("Transformation & Wellbeing", 				$selected);
produce_option("Travel Agent - corporate", 				$selected);
produce_option("Travel Agent - retail", 				$selected);
produce_option("Travel Industry Agent/Consultant", 			$selected);
produce_option("Tree Surgeon", 						$selected);
produce_option("Tutor", 						$selected);
produce_option("TV Antennas/Service", 					$selected);
produce_option("Tyre Dealer", 						$selected);
produce_option("Vehicle & Equipment Finance", 				$selected);
produce_option("Vehicle Broker", 					$selected);
produce_option("Vehicle Detailer", 					$selected);
produce_option("Vehicle Finance", 					$selected);
produce_option("Vehicle Tracking - GPS", 				$selected);
produce_option("Vehicles - New", 					$selected);
produce_option("Vendors Agent", 					$selected);
produce_option("Video Production", 					$selected);
produce_option("Videography", 						$selected);
produce_option("Videos or Photography", 				$selected);
produce_option("Virtual Assistant", 					$selected);
produce_option("Virtual CEO", 						$selected);
produce_option("Virtual CFO", 						$selected);
produce_option("Visual Communications", 				$selected);
produce_option("Visual Media", 						$selected);
produce_option("Vocal Coach", 						$selected);
produce_option("Waste Elimination", 					$selected);
produce_option("Water Pressure Cleaning", 				$selected);
produce_option("Waterproofing Consultant", 				$selected);
produce_option("Web and Mobile App Development", 			$selected);
produce_option("Web Design", 						$selected);
produce_option("Web Design & Development", 				$selected);
produce_option("Web Design and Marketing", 				$selected);
produce_option("Web Development", 					$selected);
produce_option("Web Services", 						$selected);
produce_option("Welding and Fabrication", 				$selected);
produce_option("Welding Fabrication and Engineering", 			$selected);
produce_option("Wellness Consultant", 					$selected);
produce_option("Wellness Retreat", 					$selected);
produce_option("Wheelie Bin Cleaner", 					$selected);
produce_option("Wills", 						$selected);
produce_option("Wills & Estates", 					$selected);
produce_option("Window Cleaner", 					$selected);
produce_option("Window Furnishings", 					$selected);
produce_option("Window Treatment", 					$selected);
produce_option("Windscreen / Window Tinting", 				$selected);
produce_option("Wine Sales", 						$selected);
produce_option("Women's Fashions", 					$selected);
produce_option("Workplace Health & Safety Consultant", 			$selected);
produce_option("Workplace Relationships Consultant", 			$selected);
produce_option("Workwear & Uniforms", 					$selected);
produce_option("Yoga Teacher", 						$selected);
 
require $_SERVER['DOCUMENT_ROOT']."/components/inputs/pieces/selects/pieces/close_select_unset_arguments.php";