<?php
if(!isset($_SESSION)){session_start();}
require $_SERVER['DOCUMENT_ROOT']."/components/inputs/pieces/selects/pieces/open_select_and_include_functions.php";
		
produce_option("Accounting", 				$selected);
produce_option("Airlines/Aviation", 			$selected);
produce_option("Alternative Dispute Resolution",	$selected);
produce_option("Alternative Medicine", 			$selected);
produce_option("Animation", 				$selected);
produce_option("Apparel & Fashion", 			$selected);
produce_option("Architecture & Planning", 		$selected);
produce_option("Arts & Crafts", 			$selected);
produce_option("Automotive", 				$selected);
produce_option("Aviation and Aerospace", 		$selected);
produce_option("Banking", 				$selected);
produce_option("Biotechnology", 			$selected);
produce_option("Broadcast Media", 			$selected);
produce_option("Building Materials", 			$selected);
produce_option("Business Supplies & Equipment", 	$selected);
produce_option("Capital Markets", 			$selected);
produce_option("Chemicals", 				$selected);
produce_option("Civic and Social Organization", 	$selected);
produce_option("Civil Engineering", 			$selected);
produce_option("Commercial Real Estate", 		$selected);
produce_option("Computer & Network Security", 		$selected);
produce_option("Computer Games", 			$selected);
produce_option("Computer Hardware", 			$selected);
produce_option("Computer Networking", 			$selected);
produce_option("Computer Software", 			$selected);
produce_option("Construction", 				$selected);
produce_option("Consumer Elecronics", 			$selected);
produce_option("Consumer Goods", 			$selected);
produce_option("Consumer Services", 			$selected);
produce_option("Cosmetics", 				$selected);
produce_option("Dairy", 				$selected);
produce_option("Defense & Space", 			$selected);
produce_option("Design", 				$selected);
produce_option("E-learning", 				$selected);
produce_option("Education Management", 			$selected);
produce_option("Electrical & Electronic Manufacturing", $selected);
produce_option("Entertainment", 			$selected);
produce_option("Enviromental Services", 		$selected);
produce_option("Events Services", 			$selected);
produce_option("Executive Office", 			$selected);
produce_option("Facilities Services", 			$selected);
produce_option("Farming", 				$selected);
produce_option("Financial Services", 			$selected);
produce_option("Fine Art", 				$selected);
produce_option("Fishery", 				$selected);
produce_option("Food & Beverages", 			$selected);
produce_option("Food Production", 			$selected);
produce_option("Fund-Raising", 				$selected);
produce_option("Furniture", 				$selected);
produce_option("Gambling & Casinos", 			$selected);
produce_option("Glass, Ceramics & Concrete", 		$selected);
produce_option("Government Administration", 		$selected);
produce_option("Government Relations", 			$selected);
produce_option("Graphic Design", 			$selected);
produce_option("Health, Welness & Fitness", 		$selected);
produce_option("Higher Education", 			$selected);
produce_option("Hospital & Health Care", 		$selected);
produce_option("Hospitality", 				$selected);
produce_option("Human Resources", 			$selected);
produce_option("Import and Export", 			$selected);
produce_option("Individual & Family Services", 		$selected);
produce_option("Industrial Automation", 		$selected);
produce_option("Information Services", 			$selected);
produce_option("Information Technology and Services", 	$selected);
produce_option("Insurance", 				$selected);
produce_option("International Affairs", 		$selected);
produce_option("International Trade and Development", 	$selected);
produce_option("Internet", 				$selected);
produce_option("Investmend Management", 		$selected);
produce_option("Investment Banking", 			$selected);
produce_option("Judiciary", 				$selected);
produce_option("Law Enforcement", 			$selected);
produce_option("Law Practice", 				$selected);
produce_option("Legal Services", 			$selected);
produce_option("Legislative Office", 			$selected);
produce_option("Leisure, Travel & Turism", 		$selected);
produce_option("Libraries", 				$selected);
produce_option("Logistics & Supply Chain", 		$selected);
produce_option("Luxury Goods & Jewelry", 		$selected);
produce_option("Machinery", 				$selected);
produce_option("Management Consulting", 		$selected);
produce_option("Maritime", 				$selected);
produce_option("Market Research", 			$selected);
produce_option("Marketing & Advertising", 		$selected);
produce_option("Mechanical or Industrial Engineering", 	$selected);
produce_option("Media Production", 			$selected);
produce_option("Medical Device", 			$selected);
produce_option("Medical Practice", 			$selected);
produce_option("Mental Health Care", 			$selected);
produce_option("Military", 				$selected);
produce_option("Mining & Metals", 			$selected);
produce_option("Motion Pictures & Film", 		$selected);
produce_option("Museums and Institutions", 		$selected);
produce_option("Music", 				$selected);
produce_option("Nanotechnology", 			$selected);
produce_option("Newspapers", 				$selected);
produce_option("Non-profit Organization Management", 	$selected);
produce_option("Oil & Energy", 				$selected);
produce_option("Online Media", 				$selected);
produce_option("Outsourcing/Offshoring", 		$selected);
produce_option("Package/Freight Delivery", 		$selected);
produce_option("Packaging and Containers", 		$selected);
produce_option("Paper & Forest Products", 		$selected);
produce_option("Performing Arts", 			$selected);
produce_option("Pharmaceuticals", 			$selected);
produce_option("Philanthropy", 				$selected);
produce_option("Photography", 				$selected);
produce_option("Plastics", 				$selected);
produce_option("Political Organization", 		$selected);
produce_option("Primary/Secondary Education", 		$selected);
produce_option("Printing", 				$selected);
produce_option("Professional Training & Coaching", 	$selected);
produce_option("Program Development", 			$selected);
produce_option("Public Policy", 			$selected);
produce_option("Public Relations and Communications", 	$selected);
produce_option("Public Safety", 			$selected);
produce_option("Publishing", 				$selected);
produce_option("Railroad Manufacture", 			$selected);
produce_option("Ranching", 				$selected);
produce_option("Real Estate", 				$selected);
produce_option("Recreational Facilities & Services", 	$selected);
produce_option("Religious Institutions", 		$selected);
produce_option("Renewables & Envirnoment", 		$selected);
produce_option("Research", 				$selected);
produce_option("Restaurants", 				$selected);
produce_option("Retail", 				$selected);
produce_option("Security & Investigations", 		$selected);
produce_option("Semiconductors", 			$selected);
produce_option("Shipbuilding", 				$selected);
produce_option("Sporting Goods", 			$selected);
produce_option("Staffing & Recruiting", 		$selected);
produce_option("Supermarkets", 				$selected);
produce_option("Telecommunications", 			$selected);
produce_option("Textiles", 				$selected);
produce_option("Think Thanks", 				$selected);
produce_option("Tobacco", 				$selected);
produce_option("Translation & Localisation", 		$selected);
produce_option("Transportation/Trucking/Railroad", 	$selected);
produce_option("Utilities", 				$selected);
produce_option("Venture Capital & Private Equity", 	$selected);
produce_option("Veterinary", 				$selected);
produce_option("Warehousing", 				$selected);
produce_option("Wholesale", 				$selected);
produce_option("Wine & Spirits", 			$selected);
produce_option("Wireless", 				$selected);
produce_option("Writing & Editing", 			$selected);

require $_SERVER['DOCUMENT_ROOT']."/components/inputs/pieces/selects/pieces/close_select_unset_arguments.php";